config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, except: [ :new, :create, :destroy ]
  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @transactions = current_user.try(:transactions)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if current_user %>
    <h1>Welcome, <%= current_user.name %>!</h1>

    <%= link_to "Add transaction", new_transaction_path %>
    <table>
        <tr>
            <th>Amount</th>
            <th>Description</th>
            <th>Category</th>
            <th>Created at</th>
            <th></th>
            <th></th>
        </tr>
        <% @transactions.each do |transaction| %>
            <tr>
                <td><%= number_to_currency transaction.amount/100.0, format: "%n %u", unit: "₽" %></td>
                <td><%= transaction.description %></td>
                <td><%= transaction.category %></td>
                <td><%= transaction.created_at.localtime.strftime("%-d.%m.%Y %k:%M %Z") %></td>
                <td><%= link_to "Edit", edit_transaction_path(transaction) %></td>
                <td><%= link_to "Delete", transaction, method: :delete, data: { confirm: "Are you sure?" } %></td>
            </tr>
        <% end %>
    </table>

    <p><%= link_to "Logout", destroy_user_session_url, method: :delete %></p>
    
<% else %>
    <p>Please, <%= link_to "Register", new_user_registration_path %> or <%= link_to "Log in", new_user_session_path %></p>
<% end %>